name:  Push tag & Create release

on:
  push:
    branches:
      - main   
jobs:
   
   
  build:
    name: build APK
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}                                  
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create new Tag 
        run: git tag v3.0.4

      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v3.0.4
          release_name:  v3.0.4
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
